/*
 * BeatSaver API
 *
 * WIP  If you want to keep any kind of mirror instead of making 100s of requests instead consider subscribing to the websocket api. wss://ws.beatsaver.com/maps  Messages will be in the style {\"type\": \"MAP_UPDATE\", \"msg\": __MAP_DATA_HERE__}
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MapDetailWithOrder {
    #[serde(rename = "map", skip_serializing_if = "Option::is_none")]
    pub map: Option<Box<crate::models::MapDetail>>,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<serde_json::Value>,
}

impl MapDetailWithOrder {
    pub fn new() -> MapDetailWithOrder {
        MapDetailWithOrder {
            map: None,
            order: None,
        }
    }
}
