/*
 * BeatSaver API
 *
 * WIP  If you want to keep any kind of mirror instead of making 100s of requests instead consider subscribing to the websocket api. wss://ws.beatsaver.com/maps  Messages will be in the style {\"type\": \"MAP_UPDATE\", \"msg\": __MAP_DATA_HERE__}
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaylistStats {
    #[serde(rename = "avgScore", skip_serializing_if = "Option::is_none")]
    pub avg_score: Option<serde_json::Value>,
    #[serde(rename = "downVotes", skip_serializing_if = "Option::is_none")]
    pub down_votes: Option<i32>,
    #[serde(rename = "mapperCount", skip_serializing_if = "Option::is_none")]
    pub mapper_count: Option<i64>,
    #[serde(rename = "maxNps", skip_serializing_if = "Option::is_none")]
    pub max_nps: Option<f64>,
    #[serde(rename = "maxNpsTwoDP", skip_serializing_if = "Option::is_none")]
    pub max_nps_two_dp: Option<f64>,
    #[serde(rename = "minNps", skip_serializing_if = "Option::is_none")]
    pub min_nps: Option<f64>,
    #[serde(rename = "minNpsTwoDP", skip_serializing_if = "Option::is_none")]
    pub min_nps_two_dp: Option<f64>,
    #[serde(rename = "scoreOneDP", skip_serializing_if = "Option::is_none")]
    pub score_one_dp: Option<serde_json::Value>,
    #[serde(rename = "totalDuration", skip_serializing_if = "Option::is_none")]
    pub total_duration: Option<i32>,
    #[serde(rename = "totalMaps", skip_serializing_if = "Option::is_none")]
    pub total_maps: Option<i32>,
    #[serde(rename = "upVotes", skip_serializing_if = "Option::is_none")]
    pub up_votes: Option<i32>,
}

impl PlaylistStats {
    pub fn new() -> PlaylistStats {
        PlaylistStats {
            avg_score: None,
            down_votes: None,
            mapper_count: None,
            max_nps: None,
            max_nps_two_dp: None,
            min_nps: None,
            min_nps_two_dp: None,
            score_one_dp: None,
            total_duration: None,
            total_maps: None,
            up_votes: None,
        }
    }
}
