/*
 * BeatSaver API
 *
 * WIP  If you want to keep any kind of mirror instead of making 100s of requests instead consider subscribing to the websocket api. wss://ws.beatsaver.com/maps  Messages will be in the style {\"type\": \"MAP_UPDATE\", \"msg\": __MAP_DATA_HERE__}
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaylistPage {
    #[serde(rename = "maps", skip_serializing_if = "Option::is_none")]
    pub maps: Option<Vec<models::MapDetailWithOrder>>,
    #[serde(rename = "playlist", skip_serializing_if = "Option::is_none")]
    pub playlist: Option<Box<models::PlaylistFull>>,
}

impl PlaylistPage {
    pub fn new() -> PlaylistPage {
        PlaylistPage {
            maps: None,
            playlist: None,
        }
    }
}
