/*
 * BeatSaver API
 *
 * WIP  If you want to keep any kind of mirror instead of making 100s of requests instead consider subscribing to the websocket api. wss://ws.beatsaver.com/maps  Messages will be in the style {\"type\": \"MAP_UPDATE\", \"msg\": __MAP_DATA_HERE__}
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserStats {
    #[serde(rename = "avgBpm", skip_serializing_if = "Option::is_none")]
    pub avg_bpm: Option<serde_json::Value>,
    #[serde(rename = "avgDuration", skip_serializing_if = "Option::is_none")]
    pub avg_duration: Option<serde_json::Value>,
    #[serde(rename = "avgScore", skip_serializing_if = "Option::is_none")]
    pub avg_score: Option<serde_json::Value>,
    #[serde(rename = "diffStats", skip_serializing_if = "Option::is_none")]
    pub diff_stats: Option<Box<models::UserDiffStats>>,
    #[serde(rename = "firstUpload", skip_serializing_if = "Option::is_none")]
    pub first_upload: Option<String>,
    #[serde(rename = "lastUpload", skip_serializing_if = "Option::is_none")]
    pub last_upload: Option<String>,
    #[serde(rename = "rankedMaps", skip_serializing_if = "Option::is_none")]
    pub ranked_maps: Option<i32>,
    #[serde(rename = "totalDownvotes", skip_serializing_if = "Option::is_none")]
    pub total_downvotes: Option<i32>,
    #[serde(rename = "totalMaps", skip_serializing_if = "Option::is_none")]
    pub total_maps: Option<i32>,
    #[serde(rename = "totalUpvotes", skip_serializing_if = "Option::is_none")]
    pub total_upvotes: Option<i32>,
}

impl UserStats {
    pub fn new() -> UserStats {
        UserStats {
            avg_bpm: None,
            avg_duration: None,
            avg_score: None,
            diff_stats: None,
            first_upload: None,
            last_upload: None,
            ranked_maps: None,
            total_downvotes: None,
            total_maps: None,
            total_upvotes: None,
        }
    }
}
